// <auto-generated />
using System;
using ApiTaskSchedule.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiTaskSchedule.Migrations
{
    [DbContext(typeof(TaskSchedulerDbContext))]
    [Migration("20190322213538_jobdescription")]
    partial class jobdescription
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ApiTaskSchedule.DB.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<Guid>("OwnerId");

                    b.Property<int>("PercentCompleted");

                    b.Property<int>("Status");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("ApiTaskSchedule.DB.JobOutput", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("Content");

                    b.Property<Guid>("JobId");

                    b.Property<DateTime>("Time");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("JobOutputs");
                });

            modelBuilder.Entity("ApiTaskSchedule.DB.JobOutput", b =>
                {
                    b.HasOne("ApiTaskSchedule.DB.Job", "Job")
                        .WithMany("JobOutputs")
                        .HasForeignKey("JobId")
                        .HasConstraintName("FK_Job_JobOutputs");
                });
#pragma warning restore 612, 618
        }
    }
}
